package com.example.beautysalon;

public class ResponseCode {
    public static final int SIGN_IN_SUCCESS = 2000;
    public static final int SIGN_UP_SUCCESS = 2001;
    public static final int UPDATE_USER_SUCCESS = 2002;
    public static final int DELETE_SUCCESS = 2003;
    public static final int REQUEST_BARBERSHOP_DATA_SUCCESS = 2004;
    public static final int REQUEST_STYLIST_DATA_SUCCESS = 2005;
    public static final int REQUEST_COMMENT_DATA_SUCCESS = 2006;
    public static final int REQUEST_COUPON_DISTRIBUTION_DATA_SUCCESS = 2007;
    public static final int RECEIVE_COUPON_SUCCESS = 2008;
    public static final int REQUEST_COUPON_DATA_SUCCESS = 2009;
    public static final int REQUEST_SIGN_IN_DATA_SUCCESS = 2010;
    public static final int RECEIVE_POINTS_SUCCESS = 2011;
    public static final int REQUEST_POINTS_DATA_SUCCESS= 2012;
    public static final int REQUEST_USER_DATA_SUCCESS= 2013;
    public static final int TOP_UP_SUCCESS= 2014;
    public static final int REQUEST_BALANCE_DATA_SUCCESS= 2015;
    public static final int REQUEST_BUSINESS_HOURS_DATA_SUCCESS= 2016;
    public static final int RESERVE_SUCCESS= 2017;
    public static final int CANCEL_RESERVE_SUCCESS= 2018;
    public static final int PAY_SUCCESS= 2019;
    public static final int REQUEST_RESERVATION_DATA_SUCCESS = 2020;
    public static final int REQUEST_VALID_POINTS_COUPON_SUCCESS = 2021;
    public static final int EVALUATE_SUCCESS = 2022;
    public static final int REQUEST_USER_COMMENT_SUCCESS = 2023;
    public static final int UPDATE_AVATAR_SUCCESS = 2024;
    public static final int REQUEST_STYLIST_RESERVATION_SUCCESS = 2025;
    public static final int REQUEST_STYLIST_MAIN_DATA_SUCCESS = 2026;
    public static final int UPDATE_STYLIST_SUCCESS = 2027;
    public static final int REQUEST_USER_COMMENT_DATA_SUCCESS = 2028;
    public static final int REQUEST_RESERVATION_COMMENT_DATA_SUCCESS = 2029;
    public static final int REQUEST_INFORMATION_DATA_SUCCESS = 2030;
    public static final int REQUEST_RESERVE_STATUS_SUCCESS = 2031;


    public static final int SIGN_IN_FAILED = 3000;
    public static final int SIGN_UP_FAILED = 3001;
    public static final int UPDATE_USER_FAILED = 3002;
    public static final int DELETE_FAILED = 3003;
    public static final int USER_EXIST_FAILED = 3004;
    public static final int REQUEST_BARBERSHOP_DATA_FAILED = 3005;
    public static final int REQUEST_STYLIST_DATA_FAILED = 3006;
    public static final int REQUEST_COMMENT_DATA_FAILED = 3007;
    public static final int REQUEST_COUPON_DISTRIBUTION_DATA_FAILED = 3008;
    public static final int RECEIVE_COUPON_FAILED = 3009;
    public static final int REQUEST_COUPON_DATA_FAILED = 3010;
    public static final int REQUEST_SIGN_IN_DATA_FAILED = 3011;
    public static final int RECEIVE_POINTS_FAILED = 3012;
    public static final int REQUEST_POINTS_DATA_FAILED = 3013;
    public static final int REQUEST_USER_DATA_FAILED = 3014;
    public static final int TOP_UP_FAILED= 3015;
    public static final int REQUEST_BALANCE_DATA_FAILED= 3016;
    public static final int REQUEST_BUSINESS_HOURS_DATA_FAILED= 3017;
    public static final int RESERVE_FAILED= 3018;
    public static final int CANCEL_RESERVE_FAILED= 3019;
    public static final int PAY_FAILED= 3020;
    public static final int REQUEST_RESERVATION_DATA_FAILED = 3021;
    public static final int REQUEST_VALID_POINTS_COUPON_FAILED = 3022;
    public static final int EVALUATE_FAILED = 3023;
    public static final int REQUEST_USER_COMMENT_FAILED = 3024;
    public static final int UPDATE_AVATAR_FAILED = 3025;
    public static final int REQUEST_STYLIST_RESERVATION_FAILED = 3026;
    public static final int REQUEST_STYLIST_MAIN_DATA_FAILED = 3027;
    public static final int UPDATE_STYLIST_FAILED= 3028;
    public static final int REQUEST_USER_COMMENT_DATA_FAILED = 3029;
    public static final int REQUEST_RESERVATION_COMMENT_DATA_FAILED = 3030;
    public static final int REQUEST_INFORMATION_DATA_FAILED = 3031;
    public static final int REQUEST_RESERVE_STATUS_FAILED = 3032;


    public static final int EMPTY_RESPONSE = 4000;
    public static final int SERVER_ERROR = 4001;
    public static final int REQUEST_FAILED = 4002;
    public static final int JSON_SERIALIZATION = 4003;
    public static final int EXIT_SUCCESS = 4004;
    public static final int UNCHANGED_INFORMATION = 4005;
    public static final int PAY_TWICE_ERROR = 4006;
    public static final int PHONE_EXIST_ERROR = 4007;
}
